Remove unused posA member.
This was causing a warning with -Wextra:
./diff.hh:162:60: error: missing field 'posA' initializer [-Werror,-Wmissing-field-initializers]
                    append_diff(diffs, {Diff::Keep, diag, 0});